FROM node:22-bookworm-slim

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends \
    git \
    openssh-client \
    ca-certificates \
    openssl \
    curl \
    bash \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
