import { prisma } from '../../db.js';
import { type AdminAccessContext } from '../admin-access/admin-access-control.js';
import { DASHBOARD_DEFAULT_TIMEZONE, DASHBOARD_FINANCE_PERMISSIONS, DASHBOARD_LOW_STOCK_THRESHOLD, DASHBOARD_OPERATIONS_PERMISSIONS, type DashboardQuery } from './dashboard-v2-types.js';
import { resolveDashboardQueryContext, type DashboardQueryContext } from './dashboard-v2-query.js';
import { countScopedPendingInvoices, countScopedPendingTaxReviews, listScopedTaxAlerts, restoreSelectedIdOrder } from '../tax-record/tax-record-scope-repository.js';

export type DashboardPeriod = { from: Date; to: Date; timezone: string };
export function parseDashboardPeriod(query: DashboardQuery, maxDays: number): DashboardPeriod {
  const timezone = query.timezone || DASHBOARD_DEFAULT_TIMEZONE;
  try { new Intl.DateTimeFormat('en-US', { timeZone: timezone }).format(); } catch { throw Object.assign(new Error('timezone is invalid'), { statusCode: 400 }); }
  const to = query.to ? new Date(query.to) : new Date(); const from = query.from ? new Date(query.from) : new Date(to.getTime() - 30 * 86400000);
  if (Number.isNaN(from.valueOf()) || Number.isNaN(to.valueOf())) throw Object.assign(new Error('from/to must be ISO time'), { statusCode: 400 });
  if (from >= to) throw Object.assign(new Error('from must be before to'), { statusCode: 400 });
  if (to.getTime() - from.getTime() > maxDays * 86400000) throw Object.assign(new Error(`date range exceeds ${maxDays} days`), { statusCode: 422 });
  return { from, to, timezone };
}
function orderScope(queryContext: DashboardQueryContext) {
  const { scope } = queryContext;
  if (scope.isSuperAdmin) return { ...(scope.communityIds.length ? { community_id: scope.communityIds[0] } : {}), ...(scope.pickupStoreIds.length ? { pickup_store_id: scope.pickupStoreIds[0] } : {}) };
  const scoped = [{ community_id: { in: scope.communityIds } }, { pickup_store_id: { in: scope.pickupStoreIds } }];
  return { OR: scoped };
}
const unavailable = { available: false, reason: 'permission_denied' };
export async function dashboardOverview(context: AdminAccessContext, query: DashboardQuery) {
 const queryContext = resolveDashboardQueryContext(context, query, 93); const period = queryContext.period; const scope = orderScope(queryContext); const ops = queryContext.permissions.operationsAvailable; const fin = queryContext.permissions.financeAvailable;
 const paidWhere: any = { ...scope, pay_status: 'paid', paid_at: { gte: period.from, lt: period.to } };
 const [paid, refunds] = fin || ops ? await Promise.all([prisma.order.aggregate({ where: paidWhere, _count: { id: true }, _sum: { pay_amount_cents: true } }), prisma.refund.aggregate({ where: { status: 'success', processed_at: { gte: period.from, lt: period.to }, order: scope }, _sum: { refund_amount_cents: true } })]) : [{ _count: { id: 0 }, _sum: { pay_amount_cents: 0 } }, { _sum: { refund_amount_cents: 0 } }];
 const gmv = paid._sum.pay_amount_cents ?? 0, refunded = refunds._sum.refund_amount_cents ?? 0;
 const operations = ops ? { available:true, paid_order_count: paid._count.id, group_buy_active_count: await prisma.groupBuy.count({where:{ status:'pending', ...(query.community_id ? {community_id:query.community_id}: {})}}), group_buy_success_count: await prisma.groupBuy.count({where:{status:'success'}}), group_buy_failed_count: await prisma.groupBuy.count({where:{status:'failed'}}), pending_pickup_count: await prisma.order.count({where:{...scope,pickup_type:'store',order_status:'ready'}}), pending_delivery_count:await prisma.order.count({where:{...scope,pickup_type:'delivery',order_status:{in:['paid','grouped','preparing','ready']}}}), pending_after_sale_count:await prisma.afterSaleCase.count({where:{status:{in:['submitted','reviewing']},order:scope}}), low_stock_product_count:await prisma.product.count({where:{stock:{lte:DASHBOARD_LOW_STOCK_THRESHOLD}}}), expiring_batch_count:await prisma.productBatch.count({where:{expire_at:{gte:new Date(),lte:new Date(Date.now()+7*86400000)},remaining_quantity:{gt:0}}}), low_stock_threshold:DASHBOARD_LOW_STOCK_THRESHOLD } : unavailable;
 const finance = fin ? { available:true, paid_gmv_cents:gmv, successful_refund_cents:refunded, net_collected_cents:gmv-refunded, reward_pending_cents:(await prisma.commission.aggregate({where:{status:'pending',order:scope},_sum:{final_amount_cents:true}}))._sum.final_amount_cents??0, reward_available_cents:(await prisma.commission.aggregate({where:{status:'available',order:scope},_sum:{final_amount_cents:true}}))._sum.final_amount_cents??0, withdrawal_pending_count:await prisma.withdrawal.count({where:{status:'pending'}}), withdrawal_pending_amount_cents:(await prisma.withdrawal.aggregate({where:{status:'pending'},_sum:{amount_cents:true}}))._sum.amount_cents??0, tax_review_pending_count:await countScopedPendingTaxReviews(prisma,{isSuperAdmin:queryContext.scope.isSuperAdmin,communityIds:queryContext.scope.communityIds,pickupStoreIds:queryContext.scope.pickupStoreIds},{sourceType:'withdrawal',from:period.from,to:period.to}), invoice_pending_count:await countScopedPendingInvoices(prisma,{isSuperAdmin:queryContext.scope.isSuperAdmin,communityIds:queryContext.scope.communityIds,pickupStoreIds:queryContext.scope.pickupStoreIds},{sourceType:'withdrawal',from:period.from,to:period.to}) } : unavailable;
 return { period:{from:period.from.toISOString(),to:period.to.toISOString(),timezone:period.timezone}, scope:{community_ids:context.data_scope.community_ids,pickup_store_ids:context.data_scope.pickup_store_ids,is_super_admin:context.is_super_admin}, operations, finance, warning_evidence:gmv-refunded<0?['net_collected_cents_negative']:[] };
}
export async function dashboardTrends(context: AdminAccessContext, q: DashboardQuery) { const queryContext=resolveDashboardQueryContext(context,q,31), p=queryContext.period, scope=orderScope(queryContext); const rows=await prisma.order.groupBy({by:['paid_at'],where:{...scope,pay_status:'paid',paid_at:{gte:p.from,lt:p.to}},_count:{id:true},_sum:{pay_amount_cents:true},orderBy:{paid_at:'asc'}}); const map=new Map(rows.filter(r=>r.paid_at).map(r=>[r.paid_at!.toISOString().slice(0,10),r])); const items=[] as any[]; for(let d=new Date(p.from);d<p.to;d.setUTCDate(d.getUTCDate()+1)){const date=d.toISOString().slice(0,10),r=map.get(date);items.push({date,paid_order_count:r?._count.id??0,paid_gmv_cents:r?._sum.pay_amount_cents??0,successful_refund_cents:0,net_collected_cents:r?._sum.pay_amount_cents??0});} return {items}; }
export async function dashboardAlerts(context: AdminAccessContext,q:DashboardQuery){ const queryContext=resolveDashboardQueryContext(context,q,93); orderScope(queryContext); const limit=Math.min(Math.max(Number(q.limit)||50,1),100); const taxAlerts=await prisma.$transaction(async(tx)=>{const selected=await listScopedTaxAlerts(tx,queryContext.scope,{sourceType:'withdrawal',from:queryContext.period.from,to:queryContext.period.to},limit);const hydrated=await tx.taxRecord.findMany({where:{id:{in:selected.map(row=>row.taxRecordId)}}});const ordered=restoreSelectedIdOrder(selected.map(row=>row.taxRecordId),hydrated);const details=new Map(selected.map(row=>[row.taxRecordId,row]));return ordered.map(record=>details.get(record.id)!)}); const items=[...taxAlerts.map(x=>({alert_type:x.alertType,severity:'high',target_type:'withdrawal',target_id:x.withdrawalId,title:x.alertType==='tax_review_pending'?'存在待审核税务记录':'存在待确认发票',occurred_at:x.occurredAt.toISOString(),navigation_path:'/tax-review'})),...(await prisma.withdrawal.findMany({where:{status:'pending'},select:{id:true,created_at:true},take:limit})).map(x=>({alert_type:'withdrawal_pending',severity:'high',target_type:'withdrawal',target_id:x.id,title:'存在待审核提现',occurred_at:x.created_at.toISOString(),navigation_path:'/withdrawals'})),...(await prisma.product.findMany({where:{stock:{lte:DASHBOARD_LOW_STOCK_THRESHOLD}},select:{id:true,updated_at:true},take:limit})).map(x=>({alert_type:'low_stock',severity:'medium',target_type:'product',target_id:x.id,title:'商品库存偏低',occurred_at:x.updated_at.toISOString(),navigation_path:'/inventory'}))].sort((a,b)=>a.severity.localeCompare(b.severity)||a.occurred_at.localeCompare(b.occurred_at)||a.target_id.localeCompare(b.target_id)).slice(0,limit); return {items}; }
