import { prisma } from '../../db.js';
import { type AdminAccessContext } from '../admin-access/admin-access-control.js';
import { DASHBOARD_DEFAULT_TIMEZONE, DASHBOARD_FINANCE_PERMISSIONS, DASHBOARD_LOW_STOCK_THRESHOLD, DASHBOARD_OPERATIONS_PERMISSIONS, type DashboardQuery } from './dashboard-v2-types.js';
import { resolveDashboardQueryContext, type DashboardQueryContext } from './dashboard-v2-query.js';
import { buildScopedGroupBuyWhere, buildScopedOrderWhere, buildScopedProductBatchWhere, buildScopedProductWhere, buildScopedWithdrawalWhere } from '../admin-access/admin-query-scope.js';
import { countScopedPendingInvoices, countScopedPendingTaxReviews, listScopedTaxAlerts } from '../tax-record/tax-record-scope-repository.js';

export type DashboardPeriod = { from: Date; to: Date; timezone: string };
export function parseDashboardPeriod(query: DashboardQuery, maxDays: number): DashboardPeriod {
  const timezone = query.timezone || DASHBOARD_DEFAULT_TIMEZONE;
  try { new Intl.DateTimeFormat('en-US', { timeZone: timezone }).format(); } catch { throw Object.assign(new Error('timezone is invalid'), { statusCode: 400 }); }
  const to = query.to ? new Date(query.to) : new Date(); const from = query.from ? new Date(query.from) : new Date(to.getTime() - 30 * 86400000);
  if (Number.isNaN(from.valueOf()) || Number.isNaN(to.valueOf())) throw Object.assign(new Error('from/to must be ISO time'), { statusCode: 400 });
  if (from >= to) throw Object.assign(new Error('from must be before to'), { statusCode: 400 });
  if (to.getTime() - from.getTime() > maxDays * 86400000) throw Object.assign(new Error(`date range exceeds ${maxDays} days`), { statusCode: 422 });
  return { from, to, timezone };
}
const unavailable = { available: false, reason: 'permission_denied' };
export async function dashboardOverview(context: AdminAccessContext, query: DashboardQuery) {
 const queryContext = resolveDashboardQueryContext(context, query, 93); const period = queryContext.period; const scope = buildScopedOrderWhere(queryContext); const withdrawalScope = buildScopedWithdrawalWhere(queryContext); const groupBuyScope = buildScopedGroupBuyWhere(queryContext); const productScope = buildScopedProductWhere(queryContext); const batchScope = buildScopedProductBatchWhere(queryContext); const ops = queryContext.permissions.operationsAvailable; const fin = queryContext.permissions.financeAvailable;
 const paidWhere: any = { ...scope, pay_status: 'paid', paid_at: { gte: period.from, lt: period.to } };
 const [paid, refunds] = fin || ops ? await Promise.all([prisma.order.aggregate({ where: paidWhere, _count: { id: true }, _sum: { pay_amount_cents: true } }), prisma.refund.aggregate({ where: { status: 'success', processed_at: { gte: period.from, lt: period.to }, order: scope }, _sum: { refund_amount_cents: true } })]) : [{ _count: { id: 0 }, _sum: { pay_amount_cents: 0 } }, { _sum: { refund_amount_cents: 0 } }];
 const gmv = paid._sum.pay_amount_cents ?? 0, refunded = refunds._sum.refund_amount_cents ?? 0;
 const operations = ops ? { available:true, paid_order_count: paid._count.id, group_buy_active_count: await prisma.groupBuy.count({where:{...groupBuyScope,status:'pending'}}), group_buy_success_count: await prisma.groupBuy.count({where:{...groupBuyScope,status:'success'}}), group_buy_failed_count: await prisma.groupBuy.count({where:{...groupBuyScope,status:'failed'}}), pending_pickup_count: await prisma.order.count({where:{...scope,pickup_type:'store',order_status:'ready'}}), pending_delivery_count:await prisma.order.count({where:{...scope,pickup_type:'delivery',order_status:{in:['paid','grouped','preparing','ready']}}}), pending_after_sale_count:await prisma.afterSaleCase.count({where:{status:{in:['submitted','reviewing']},order:scope}}), low_stock_product_count:await prisma.product.count({where:{...productScope,stock:{lte:DASHBOARD_LOW_STOCK_THRESHOLD}}}), expiring_batch_count:await prisma.productBatch.count({where:{...batchScope,expire_at:{gte:new Date(),lte:new Date(Date.now()+queryContext.expiringDays*86400000)},remaining_quantity:{gt:0}}}), low_stock_threshold:DASHBOARD_LOW_STOCK_THRESHOLD } : unavailable;
 const finance = fin ? { available:true, paid_gmv_cents:gmv, successful_refund_cents:refunded, net_collected_cents:gmv-refunded, reward_pending_cents:(await prisma.commission.aggregate({where:{status:'pending',order:scope},_sum:{final_amount_cents:true}}))._sum.final_amount_cents??0, reward_available_cents:(await prisma.commission.aggregate({where:{status:'available',order:scope},_sum:{final_amount_cents:true}}))._sum.final_amount_cents??0, withdrawal_pending_count:await prisma.withdrawal.count({where:{...withdrawalScope,status:'pending'}}), withdrawal_pending_amount_cents:(await prisma.withdrawal.aggregate({where:{...withdrawalScope,status:'pending'},_sum:{amount_cents:true}}))._sum.amount_cents??0, tax_review_pending_count:await countScopedPendingTaxReviews(prisma,queryContext.scope,{sourceType:'withdrawal',createdAtFromInclusive:period.from,createdAtToExclusive:period.to}), invoice_pending_count:await countScopedPendingInvoices(prisma,queryContext.scope,{sourceType:'withdrawal',createdAtFromInclusive:period.from,createdAtToExclusive:period.to}) } : unavailable;
 return { period:{from:period.from.toISOString(),to:period.to.toISOString(),timezone:period.timezone}, scope:{community_ids:context.data_scope.community_ids,pickup_store_ids:context.data_scope.pickup_store_ids,is_super_admin:context.is_super_admin}, operations, finance, warning_evidence:gmv-refunded<0?['net_collected_cents_negative']:[] };
}
export async function dashboardTrends(context: AdminAccessContext, q: DashboardQuery) { const queryContext=resolveDashboardQueryContext(context,q,31), p=queryContext.period, scope=buildScopedOrderWhere(queryContext); const rows=await prisma.order.groupBy({by:['paid_at'],where:{...scope,pay_status:'paid',paid_at:{gte:p.from,lt:p.to}},_count:{id:true},_sum:{pay_amount_cents:true},orderBy:{paid_at:'asc'}}); const map=new Map(rows.filter(r=>r.paid_at).map(r=>[r.paid_at!.toISOString().slice(0,10),r])); const items=[] as any[]; for(let d=new Date(p.from);d<p.to;d.setUTCDate(d.getUTCDate()+1)){const date=d.toISOString().slice(0,10),r=map.get(date);items.push({date,paid_order_count:r?._count.id??0,paid_gmv_cents:r?._sum.pay_amount_cents??0,successful_refund_cents:0,net_collected_cents:r?._sum.pay_amount_cents??0});} return {items}; }
const ALERT_SEVERITY_WEIGHT={critical:0,high:1,medium:2,low:3} as const;
function dashboardAlertLimit(value:string|undefined){if(value===undefined)return 50;const limit=Number(value);if(!Number.isInteger(limit)||limit<1||limit>100)throw Object.assign(new Error('limit must be an integer between 1 and 100'),{statusCode:400});return limit;}
export function taxAlertKey(row:{taxRecordId:string;alertType:string}){return `${row.taxRecordId}:${row.alertType}`;}
export async function dashboardAlerts(context: AdminAccessContext,q:DashboardQuery){ const queryContext=resolveDashboardQueryContext(context,q,93); const limit=dashboardAlertLimit(q.limit); const withdrawalScope=buildScopedWithdrawalWhere(queryContext); const taxAlerts=await listScopedTaxAlerts(prisma,queryContext.scope,{sourceType:'withdrawal',createdAtFromInclusive:queryContext.period.from,createdAtToExclusive:queryContext.period.to},limit); const items=[...taxAlerts.map(x=>({alert_type:x.alertType,severity:'high' as const,target_type:'withdrawal',target_id:x.withdrawalId,title:x.alertType==='tax_review_pending'?'存在待审核税务记录':'存在待确认发票',occurred_at:x.occurredAt.toISOString(),navigation_path:'/tax-review',identity:taxAlertKey(x)})),...(await prisma.withdrawal.findMany({where:{...withdrawalScope,status:'pending'},select:{id:true,created_at:true},take:limit,orderBy:[{created_at:'desc'},{id:'asc'}]})).map(x=>({alert_type:'withdrawal_pending',severity:'high' as const,target_type:'withdrawal',target_id:x.id,title:'存在待审核提现',occurred_at:x.created_at.toISOString(),navigation_path:'/withdrawals',identity:`${x.id}:withdrawal_pending`}))].sort((left,right)=>ALERT_SEVERITY_WEIGHT[left.severity]-ALERT_SEVERITY_WEIGHT[right.severity]||right.occurred_at.localeCompare(left.occurred_at)||left.target_id.localeCompare(right.target_id)||left.alert_type.localeCompare(right.alert_type)).slice(0,limit); return {items}; }
