import { readFileSync } from 'node:fs';
import { GLOBAL_STATIC_VERIFIERS, getStageDefinition } from './stage-registry.ts';
import { resolveReportSource } from './stage-report-source.ts';
import { parseStageArg } from './stage-args.ts';
function assert(v: unknown, m: string): asserts v { if (!v) throw new Error(m); }
function assertThrows(callback: () => unknown, expectedMessage: string): void { let actualError: unknown; try { callback(); } catch (error) { actualError = error; } assert(actualError instanceof Error, `Expected error containing: ${expectedMessage}`); assert(actualError.message.includes(expectedMessage), [`Expected error containing: ${expectedMessage}`, `Actual: ${actualError.message}`].join('\n')); }
assert(parseStageArg(['--stage=L45']) === 'L45', 'Inline stage argument must resolve');
assert(parseStageArg(['--stage', 'L46']) === 'L46', 'Split stage argument must resolve');
assert(parseStageArg(['--', '--stage=L46']) === 'L46', 'Separator stage argument must resolve');
assertThrows(() => parseStageArg([]), 'Missing required --stage=Lxx');
assertThrows(() => parseStageArg(['--stage=L99']), 'Unknown stage: L99');
const generator = readFileSync('scripts/generate-stage-report.ts', 'utf8'); const verifier = readFileSync('scripts/verify-report-publish-local.ts', 'utf8');
const l46Definition = getStageDefinition('L46'); assert(l46Definition, 'L46 must be registered'); assert(l46Definition.reportContract, 'L46 report contract must be registered'); const l46Source = resolveReportSource('L46'); assert(l46Source.sourceMode === 'git_diff', 'L46 report source must use git_diff'); assert(l46Source.businessBaseBranch === l46Definition.reportContract.businessBaseBranch, 'L46 resolver branch must match Registry'); assert(l46Source.businessBaseCommit === l46Definition.reportContract.businessBaseCommit, 'L46 resolver commit must match Registry');
const l25Source = resolveReportSource('L25', {}); assert(l25Source.sourceMode === 'legacy_manifest', 'L25 report source must use legacy manifest'); assert(l25Source.businessBaseBranch === undefined, 'L25 legacy source must not invent a branch'); assert(l25Source.businessBaseCommit === undefined, 'L25 legacy source must not invent a commit');
assert(GLOBAL_STATIC_VERIFIERS.includes('scripts/verify-report-source-resolver-local.ts'), 'Report source resolver verifier must be globally registered');
assert(generator.includes("title: 'L45 manual tax review and internal CSV export'"), 'L45 retains manifest title');
assert(generator.includes('stageManifest?.title ?? stageDefinition.title'), 'generator selects manifest then registry title');
assert(!generator.includes('${stage} 阶段目标，需结合阶段说明人工确认'), 'no generic L46 fallback');
assert(generator.includes('reportContract') && verifier.includes('definition.reportContract'), 'shared report contract');
assert(!verifier.includes('reportChangedFileBases') && !verifier.includes("?? 'HEAD~1'"), 'L46 does not fall back to HEAD~1');
assert(!verifier.includes(`report.includes('${l46Definition.title}')`), 'verifier has no hardcoded L46 title');

const compactGenerator = generator.replace(/\s+/g, ' ');
assert(/resolveReportSource\s*\(\s*stage\s*\)/.test(generator), 'Generator must resolve report source using the requested stage');
assert(/stageDefinition\.reportContract\s*\?\s*resolveReportSource\s*\(\s*stage\s*\)/.test(compactGenerator), 'Generator must resolve Registry report source only for contracted stages');
assert(/registryReportSource\??\.sourceMode\s*===\s*['"]git_diff['"]/.test(generator), 'Generator must branch on resolved git_diff source mode');
assert(/return\s+registryReportSource\.businessBaseCommit/.test(generator), 'Generator git diff base must come from resolved business base commit');
assert(/stageManifest\??\.businessBaseBranch\s*\?\?\s*registryReportSource\??\.businessBaseBranch/.test(generator), 'Generator business base branch must fall back to resolved source');
assert(/stageManifest\??\.businessBaseCommit\s*\?\?\s*registryReportSource\??\.businessBaseCommit/.test(generator), 'Generator business base commit must fall back to resolved source');
assert(/isL39Stage\s*\?\s*l39Manifest/.test(generator), 'L39 must retain its historical manifest');
assert(/stageManifest\??\.title\s*\?\?\s*stageDefinition\.title/.test(generator), 'Generator title must prefer historical manifest then Registry');
assert(!/stageDefinition!?\??\.reportContract!?\??\.businessBase(Branch|Commit)/.test(generator), 'Generator must not directly read reportContract business base fields');
for (const forbidden of ['HEAD~1', 'HEAD^']) assert(!generator.includes(forbidden), `Generator must not infer report source from ${forbidden}`);
const compactVerifier = verifier.replace(/\s+/g, ' ');
assert(/function\s+resolvePublishReportSource\s*\(\s*stageId:\s*string\s*\)/.test(compactVerifier), 'Publish verifier must define report source routing');
assert(/const\s+definition\s*=\s*getStageDefinition\s*\(\s*stageId\s*\)/.test(compactVerifier), 'Publish source routing must read the requested Stage definition');
assert(/definition\.reportContract\s*\?\s*resolveReportSource\s*\(\s*definition\.id\s*\)/.test(compactVerifier), 'Contracted Stage must resolve source from Registry contract');
assert(/:\s*resolveReportSource\s*\(\s*definition\.id\s*,\s*\{\s*\}\s*\)/.test(compactVerifier), 'Legacy Stage must explicitly opt into manifest source');
assert(/function\s+changedFilesForStage\s*\(\s*stageId:\s*string\s*\)\s*:\s*PublishChangedFiles/.test(compactVerifier), 'Publish verifier must define changed-files source routing');
assert(/const\s+source\s*=\s*resolvePublishReportSource\s*\(\s*stageId\s*\)/.test(compactVerifier), 'Changed-files routing must use resolvePublishReportSource');
assert(/source\.sourceMode\s*===\s*['\"]git_diff['\"]/.test(compactVerifier), 'Changed-files routing must branch on git_diff source mode');
assert(/base\s*:\s*source\.businessBaseCommit/.test(compactVerifier), 'git_diff changed-files base must use resolved business base commit');
assert(/gitDiffFiles\s*\(\s*source\.businessBaseCommit\s*,\s*['\"]HEAD['\"]\s*\)/.test(compactVerifier), 'git_diff changed-files must compare resolved base to HEAD');
assert(/return\s*\{\s*sourceMode\s*:\s*['\"]legacy_manifest['\"]\s*\}/.test(compactVerifier), 'Legacy changed-files routing must return only legacy_manifest mode');
console.log('Report stage routing checks passed.');
