import { readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
function assert(ok: unknown, message: string): asserts ok { if (!ok) throw new Error(`L46 verifier: ${message}`); }
const files=['docs/plans/l46-admin-business-dashboard-v2.md','apps/api/src/modules/dashboard-v2/dashboard-v2-service.ts','apps/api/src/modules/dashboard-v2/dashboard-v2-query.ts','apps/api/src/routes/admin/dashboard-v2.ts','apps/admin/src/api/adminDashboardV2.ts','apps/admin/src/pages/dashboard-v2/AdminBusinessDashboardV2Page.tsx','scripts/l46-dashboard-contract.ts'];
for(const file of files) assert(existsSync(file),`${file} missing`);
const route=readFileSync(files[3],'utf8'), service=readFileSync(files[1],'utf8'), query=readFileSync(files[2],'utf8'), contract=readFileSync(files[6],'utf8'), admin=readFileSync(files[5],'utf8'), adminClient=readFileSync(files[4],'utf8');
for(const path of ['/overview','/trends','/alerts']) assert(route.includes(path),`${path} route missing`);
assert(service.includes('Intl.DateTimeFormat') && service.includes('maxDays'), 'period validation missing');
assert(service.includes('aggregate') && service.includes('groupBy'), 'database aggregation missing');
assert(route.includes('requireAdminPermission'), 'permission guard missing');
for(const api of ['dashboardOverview','dashboardTrends','dashboardAlerts']) assert(service.includes(`function ${api}`) && service.slice(service.indexOf(`function ${api}`), service.indexOf(`function ${api}`)+600).includes('resolveDashboardQueryContext'), `${api} must use DashboardQueryContext`);
assert(query.includes('Number.isInteger(expiringDays)') && query.includes('expiringDays<1') && query.includes('expiringDays>30') && query.includes('statusCode:400'), 'invalid expiring_days must return 400 rather than clamp');
assert(service.includes('countScopedPendingTaxReviews(prisma') && service.includes('countScopedPendingInvoices(prisma'), 'overview must use scoped tax/invoice repositories');
assert(service.includes('listScopedTaxAlerts(prisma') && service.includes('taxAlertKey') && service.includes('ALERT_SEVERITY_WEIGHT'), 'alerts must use scoped tax repository, composite identity, and deterministic severity ordering');
assert(service.includes('buildScopedWithdrawalWhere') && service.includes('buildScopedGroupBuyWhere') && service.includes('buildScopedProductWhere') && service.includes('buildScopedProductBatchWhere'), 'dashboard metrics must use shared database scope builders');
const changedFiles=execFileSync('git',['diff','--name-only','7e79bd4a701b1d0a071dd9a800f759a82098a1af..HEAD'],{encoding:'utf8'}).split(/\r?\n/);
for(const forbidden of ['reports/', 'artifacts/', 'tmp/']) assert(!changedFiles.some((file)=>file.startsWith(forbidden)), `forbidden PR artifact: ${forbidden}`);
assert(admin.includes('AbortController') && adminClient.includes('requestAdminJson'), 'admin request safety/client missing');
for(const marker of ['l46_dashboard_scope_runtime=true','l46_dashboard_overview_success=true','l46_dashboard_permission_sections=true','l46_dashboard_trends_success=true','l46_dashboard_trends_stable=true','l46_dashboard_alerts_success=true','l46_dashboard_alerts_stable=true','l46_dashboard_tax_scope_db_query=true','l46_dashboard_no_sensitive_data=true','l46_dashboard_no_auto_action=true']) assert(contract.includes(marker),`marker missing: ${marker}`);
console.log('L46 dashboard static foundation checks passed.');
