import { readFileSync } from 'node:fs';
import { GLOBAL_STATIC_VERIFIERS, getStageDefinition } from './stage-registry.ts';
import { resolveReportSource } from './stage-report-source.ts';
import { parseStageArg } from './stage-args.ts';
function assert(v: unknown, m: string): asserts v { if (!v) throw new Error(m); }
function assertThrows(callback: () => unknown, expectedMessage: string): void { let actualError: unknown; try { callback(); } catch (error) { actualError = error; } assert(actualError instanceof Error, `Expected error containing: ${expectedMessage}`); assert(actualError.message.includes(expectedMessage), [`Expected error containing: ${expectedMessage}`, `Actual: ${actualError.message}`].join('\n')); }
function escapeRegExp(value: string): string { return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
assert(parseStageArg(['--stage=L45']) === 'L45', 'Inline stage argument must resolve');
assert(parseStageArg(['--stage', 'L46']) === 'L46', 'Split stage argument must resolve');
assert(parseStageArg(['--', '--stage=L46']) === 'L46', 'Separator stage argument must resolve');
assertThrows(() => parseStageArg([]), 'Missing required --stage=Lxx');
assertThrows(() => parseStageArg(['--stage=L99']), 'Unknown stage: L99');
const generator = readFileSync('scripts/generate-stage-report.ts', 'utf8'); const verifier = readFileSync('scripts/verify-report-publish-local.ts', 'utf8');
const l46Definition = getStageDefinition('L46'); assert(l46Definition, 'L46 must be registered'); assert(l46Definition.reportContract, 'L46 report contract must be registered'); const l46Source = resolveReportSource('L46'); assert(l46Source.sourceMode === 'git_diff', 'L46 report source must use git_diff'); assert(l46Source.businessBaseBranch === l46Definition.reportContract.businessBaseBranch, 'L46 resolver branch must match Registry'); assert(l46Source.businessBaseCommit === l46Definition.reportContract.businessBaseCommit, 'L46 resolver commit must match Registry');
const l25Source = resolveReportSource('L25', {}); assert(l25Source.sourceMode === 'legacy_manifest', 'L25 report source must use legacy manifest'); assert(l25Source.businessBaseBranch === undefined, 'L25 legacy source must not invent a branch'); assert(l25Source.businessBaseCommit === undefined, 'L25 legacy source must not invent a commit');
assert(GLOBAL_STATIC_VERIFIERS.includes('scripts/verify-report-source-resolver-local.ts'), 'Report source resolver verifier must be globally registered');
assert(generator.includes("title: 'L45 manual tax review and internal CSV export'"), 'L45 retains manifest title');
assert(generator.includes('stageManifest?.title ?? stageDefinition.title'), 'generator selects manifest then registry title');
assert(!generator.includes('${stage} 阶段目标，需结合阶段说明人工确认'), 'no generic L46 fallback');
assert(generator.includes('reportContract') && verifier.includes('definition.reportContract'), 'shared report contract');
assert(!verifier.includes('reportChangedFileBases') && !verifier.includes("?? 'HEAD~1'"), 'L46 does not fall back to HEAD~1');
assert(!verifier.includes(`report.includes('${l46Definition.title}')`), 'verifier has no hardcoded L46 title');

const compactGenerator = generator.replace(/\s+/g, ' ');
assert(/resolveReportSource\s*\(\s*stage\s*\)/.test(generator), 'Generator must resolve report source using the requested stage');
assert(/stageDefinition\.reportContract\s*\?\s*resolveReportSource\s*\(\s*stage\s*\)/.test(compactGenerator), 'Generator must resolve Registry report source only for contracted stages');
assert(/registryReportSource\??\.sourceMode\s*===\s*['"]git_diff['"]/.test(generator), 'Generator must branch on resolved git_diff source mode');
assert(/return\s+registryReportSource\.businessBaseCommit/.test(generator), 'Generator git diff base must come from resolved business base commit');
assert(/stageManifest\??\.businessBaseBranch\s*\?\?\s*registryReportSource\??\.businessBaseBranch/.test(generator), 'Generator business base branch must fall back to resolved source');
assert(/stageManifest\??\.businessBaseCommit\s*\?\?\s*registryReportSource\??\.businessBaseCommit/.test(generator), 'Generator business base commit must fall back to resolved source');
assert(/isL39Stage\s*\?\s*l39Manifest/.test(generator), 'L39 must retain its historical manifest');
assert(/stageManifest\??\.title\s*\?\?\s*stageDefinition\.title/.test(generator), 'Generator title must prefer historical manifest then Registry');
assert(!/stageDefinition!?\??\.reportContract!?\??\.businessBase(Branch|Commit)/.test(generator), 'Generator must not directly read reportContract business base fields');
for (const forbidden of ['HEAD~1', 'HEAD^']) assert(!generator.includes(forbidden), `Generator must not infer report source from ${forbidden}`);
const compactVerifier = verifier.replace(/\s+/g, ' ');
assert(/function\s+resolvePublishReportSource\s*\(\s*stageId:\s*string\s*\)/.test(compactVerifier), 'Publish verifier must define report source routing');
assert(/const\s+definition\s*=\s*getStageDefinition\s*\(\s*stageId\s*\)/.test(compactVerifier), 'Publish source routing must read the requested Stage definition');
assert(/definition\.reportContract\s*\?\s*resolveReportSource\s*\(\s*definition\.id\s*\)/.test(compactVerifier), 'Contracted Stage must resolve source from Registry contract');
assert(/:\s*resolveReportSource\s*\(\s*definition\.id\s*,\s*\{\s*\}\s*\)/.test(compactVerifier), 'Legacy Stage must explicitly opt into manifest source');
assert(/function\s+changedFilesForStage\s*\(\s*stageId:\s*string\s*\)\s*:\s*PublishChangedFiles/.test(compactVerifier), 'Publish verifier must define changed-files source routing');
assert(/const\s+source\s*=\s*resolvePublishReportSource\s*\(\s*stageId\s*\)/.test(compactVerifier), 'Changed-files routing must use resolvePublishReportSource');
assert(/source\.sourceMode\s*===\s*['"]git_diff['"]/.test(compactVerifier), 'Changed-files routing must branch on git_diff source mode');
assert(/base\s*:\s*source\.businessBaseCommit/.test(compactVerifier), 'git_diff changed-files base must use resolved business base commit');
assert(/gitDiffFiles\s*\(\s*source\.businessBaseCommit\s*,\s*['"]HEAD['"]\s*\)/.test(compactVerifier), 'git_diff changed-files must compare resolved base to HEAD');
assert(/return\s*\{\s*sourceMode\s*:\s*['"]legacy_manifest['"]\s*\}/.test(compactVerifier), 'Legacy changed-files routing must return only legacy_manifest mode');
const commonValidatorStart = compactVerifier.indexOf('function validateCommonReport');
const commonValidatorEnd = compactVerifier.indexOf('function validateL43Report', commonValidatorStart);
assert(commonValidatorStart >= 0, 'Publish verifier must define common report validation');
assert(commonValidatorEnd > commonValidatorStart, 'Common report validation must end before L43 validation');
const commonValidator = compactVerifier.slice(commonValidatorStart, commonValidatorEnd);
assert(/const\s+changedFiles\s*=\s*changedFilesForStage\s*\(\s*definition\.id\s*\)/.test(commonValidator), 'Common report validation must resolve changed-files by Stage');
assert(/if\s*\(\s*changedFiles\.sourceMode\s*===\s*['"]git_diff['"]\s*\)\s*assertSetEqual\s*\(\s*changedFiles\.files\s*,\s*reportFiles/.test(commonValidator), 'git_diff reports must compare exact changed-file sets');
const exactSetComparisons = commonValidator.match(/assertSetEqual\s*\(/g) ?? [];
assert(exactSetComparisons.length === 1, 'Common report validation must perform one git_diff exact-set comparison');
assert(/else\s*\{\s*assert\s*\(\s*reportFiles\.length\s*>\s*0/.test(commonValidator), 'Legacy reports must contain manifest changed-files');
assert(commonValidator.includes('!report.includes'), 'Legacy report validation must reject unresolved report-source output');
assert(commonValidator.includes('has no configured report source'), 'Legacy report validation must detect unresolved report-source output');
assert(commonValidator.includes('报告生成 commit：${gitOutput'), 'Common report validation must check the report generation commit');
assert(/gitOutput\s*\(\s*\[\s*['"]rev-parse['"]\s*,\s*['"]HEAD['"]\s*\]\s*\)/.test(commonValidator), 'Common report validation must compare generation commit with HEAD');
const l43ValidatorStart = compactVerifier.indexOf('function validateL43Report');
const l43ValidatorEnd = compactVerifier.indexOf('function validateL44Report', l43ValidatorStart);
const l44ValidatorStart = compactVerifier.indexOf('function validateL44Report');
const l44ValidatorEnd = compactVerifier.indexOf('function validateL45Report', l44ValidatorStart);
const l45ValidatorStart = compactVerifier.indexOf('function validateL45Report');
const l45ValidatorEnd = compactVerifier.indexOf('function validateL46Report', l45ValidatorStart);
const l46ValidatorStart = compactVerifier.indexOf('function validateL46Report');
const l46ValidatorEnd = compactVerifier.indexOf('const scannerDefinitionFixture', l46ValidatorStart);
for (const [start, end, name] of [[l43ValidatorStart, l43ValidatorEnd, 'L43'], [l44ValidatorStart, l44ValidatorEnd, 'L44'], [l45ValidatorStart, l45ValidatorEnd, 'L45'], [l46ValidatorStart, l46ValidatorEnd, 'L46']] as const) {
  assert(start >= 0, `${name} report validator must exist`);
  assert(end > start, `${name} report validator must have an end boundary`);
}
const l43Validator = compactVerifier.slice(l43ValidatorStart, l43ValidatorEnd);
const l44Validator = compactVerifier.slice(l44ValidatorStart, l44ValidatorEnd);
const l45Validator = compactVerifier.slice(l45ValidatorStart, l45ValidatorEnd);
const l46Validator = compactVerifier.slice(l46ValidatorStart, l46ValidatorEnd);
for (const [validator, stageId] of [[l43Validator, 'L43'], [l44Validator, 'L44'], [l45Validator, 'L45'], [l46Validator, 'L46']] as const) {
  assert(new RegExp(`resolveReportSource\\s*\\(\\s*['"]${stageId}['"]\\s*\\)`).test(validator), `${stageId} report validator must resolve its report source`);
  assert(!/reportContract\s*(?:!|\?)?\s*\.\s*businessBase(?:Branch|Commit)/.test(validator), `${stageId} report validator must not directly read reportContract base fields`);
}
const l46DefinitionMatch = l46Validator.match(/const\s+([A-Za-z_$][\w$]*)\s*=\s*getStageDefinition\s*\(\s*['"]L46['"]\s*\)/);
assert(l46DefinitionMatch, 'L46 report validator must read its Registry definition');
const l46DefinitionVariable = l46DefinitionMatch[1];
const l46DefinitionVariablePattern = escapeRegExp(l46DefinitionVariable);
const l46TitleInterpolation = `\\$\\{\\s*${l46DefinitionVariablePattern}\\s*\\.\\s*title\\s*\\}`;
assert(new RegExp(`注册阶段标题\\s*：\\s*${l46TitleInterpolation}`).test(l46Validator), 'L46 report validator must interpolate the registered title');
assert(new RegExp(`本阶段目标\\s*：\\s*${l46TitleInterpolation}`).test(l46Validator), 'L46 report validator must interpolate the registered goal');
const l46SourceMatch = l46Validator.match(/const\s+([A-Za-z_$][\w$]*)\s*=\s*resolveReportSource\s*\(\s*['"]L46['"]\s*\)/);
assert(l46SourceMatch, 'L46 report validator must resolve its report source');
const l46SourceVariable = l46SourceMatch[1];
const l46SourceVariablePattern = escapeRegExp(l46SourceVariable);
assert(new RegExp(`${l46SourceVariablePattern}\\s*\\.\\s*sourceMode\\s*===\\s*['"]git_diff['"]`).test(l46Validator), 'L46 report validator must require a git_diff source');
assert(new RegExp(`业务稳定分支\\s*：\\s*\\$\\{\\s*${l46SourceVariablePattern}\\s*\\.\\s*businessBaseBranch\\s*\\}`).test(l46Validator), 'L46 report validator must interpolate the resolved business base branch');
assert(new RegExp(`业务稳定 commit\\s*：\\s*\\$\\{\\s*${l46SourceVariablePattern}\\s*\\.\\s*businessBaseCommit\\s*\\}`).test(l46Validator), 'L46 report validator must interpolate the resolved business base commit');
for (const value of [l46Definition.title, l46Source.businessBaseBranch, l46Source.businessBaseCommit]) assert(!l46Validator.includes(value), 'L46 report validator must not hardcode Registry or resolver metadata');
assert(new RegExp(`${escapeRegExp('$definition')}\\s*\\.\\s*title`).test('$definition.title'), 'Escaped identifier fixture must match a dollar-prefixed identifier');
const stageWorkflow = readFileSync('scripts/stage-workflow.ts', 'utf8');
const compactWorkflow = stageWorkflow.replace(/\s+/g, ' ');
const reportStageStart = compactWorkflow.indexOf('function runReportStage');
const reportStageEnd = compactWorkflow.indexOf('function runReportVerifier', reportStageStart);
const reportVerifierStart = compactWorkflow.indexOf('function runReportVerifier');
const reportVerifierEnd = compactWorkflow.indexOf('function runReportPublish', reportVerifierStart);
const workflowMainStart = compactWorkflow.indexOf('function main');
const workflowMainEnd = compactWorkflow.indexOf('main();', workflowMainStart);
for (const [start, end, name] of [[reportStageStart, reportStageEnd, 'report stage'], [reportVerifierStart, reportVerifierEnd, 'report verifier'], [workflowMainStart, workflowMainEnd, 'workflow main']] as const) {
  assert(start >= 0, `${name} workflow block must exist`);
  assert(end > start, `${name} workflow block must have an end boundary`);
}
const reportStageBlock = compactWorkflow.slice(reportStageStart, reportStageEnd);
const reportVerifierBlock = compactWorkflow.slice(reportVerifierStart, reportVerifierEnd);
const workflowMainBlock = compactWorkflow.slice(workflowMainStart, workflowMainEnd);
const reportStageParameterMatch = reportStageBlock.match(/function\s+runReportStage\s*\(\s*([A-Za-z_$][\w$]*)\s*:\s*string\s*\)/);
assert(reportStageParameterMatch, 'Report stage workflow must accept a Stage parameter');
const reportStageParameterPattern = escapeRegExp(reportStageParameterMatch[1]);
assert(reportStageBlock.includes('report:stage'), 'Report stage workflow must invoke report generation');
assert(new RegExp(`--stage=\\$\\{\\s*${reportStageParameterPattern}\\s*\\}`).test(reportStageBlock), 'Report stage workflow must forward its requested Stage');
const reportVerifierParameterMatch = reportVerifierBlock.match(/function\s+runReportVerifier\s*\(\s*([A-Za-z_$][\w$]*)\s*:\s*string\s*\)/);
assert(reportVerifierParameterMatch, 'Report verifier workflow must accept a Stage parameter');
const reportVerifierParameterPattern = escapeRegExp(reportVerifierParameterMatch[1]);
assert(reportVerifierBlock.includes('scripts/verify-report-publish-local.ts'), 'Report verifier workflow must invoke the report publish verifier');
assert(new RegExp(`--stage=\\$\\{\\s*${reportVerifierParameterPattern}\\s*\\}`).test(reportVerifierBlock), 'Report verifier workflow must forward its requested Stage');
assert(reportVerifierBlock.includes('Report publish verification passed.'), 'Report verifier workflow must require its machine success marker');
const workflowArgsMatch = workflowMainBlock.match(/const\s+([A-Za-z_$][\w$]*)\s*=\s*parseArgs\s*\(/);
assert(workflowArgsMatch, 'Workflow main must parse its arguments');
const workflowArgsPattern = escapeRegExp(workflowArgsMatch[1]);
const publishBranchStartMatch = new RegExp(`if\\s*\\(\\s*${workflowArgsPattern}\\s*\\.\\s*publish\\s*\\)\\s*\\{`).exec(workflowMainBlock);
assert(publishBranchStartMatch, 'Workflow main must have a publish branch');
const publishBranchStart = publishBranchStartMatch.index;
const publishBranchEnd = workflowMainBlock.indexOf('return;', publishBranchStart);
assert(publishBranchEnd > publishBranchStart, 'Workflow publish branch must end after it starts');
const publishBranch = workflowMainBlock.slice(publishBranchStart, publishBranchEnd);
const stageCall = new RegExp(`runReportStage\\s*\\(\\s*${workflowArgsPattern}\\s*\\.\\s*stage\\s*!?\\s*\\)`).exec(publishBranch);
const verifierCall = new RegExp(`runReportVerifier\\s*\\(\\s*${workflowArgsPattern}\\s*\\.\\s*stage\\s*!?\\s*\\)`).exec(publishBranch);
const publishCall = new RegExp(`runReportPublish\\s*\\(\\s*${workflowArgsPattern}\\s*\\)`).exec(publishBranch);
assert(stageCall && verifierCall && publishCall, 'Workflow publish branch must forward one parsed Stage through report generation, verification, and publish');
assert(stageCall.index < verifierCall.index && verifierCall.index < publishCall.index, 'Workflow publish branch must generate, verify, then publish reports');
const publishStageMatch = verifier.match(/const\s+([A-Za-z_$][\w$]*)\s*=\s*parseStageArg\s*\(/);
assert(publishStageMatch, 'Publish verifier must parse one requested Stage');
const publishStagePattern = escapeRegExp(publishStageMatch[1]);
const publishReportMatch = compactVerifier.match(new RegExp(`const\\s+([A-Za-z_$][\\w$]*)\\s*=\\s*validateCommonReport\\s*\\(\\s*${publishStagePattern}\\s*\\)`));
assert(publishReportMatch, 'Publish verifier must validate the common report before Stage dispatch');
const publishReportPattern = escapeRegExp(publishReportMatch[1]);
const dispatchStart = compactVerifier.indexOf(publishReportMatch[0]);
const dispatchEnd = compactVerifier.indexOf('const stageWorkflowSource', dispatchStart);
assert(dispatchStart >= 0 && dispatchEnd > dispatchStart, 'Publish verifier Stage dispatch block must have stable boundaries');
const dispatchBlock = compactVerifier.slice(dispatchStart, dispatchEnd);
for (const stageId of ['L43', 'L44', 'L45', 'L46'] as const) {
  const dispatchPattern = new RegExp(`if\\s*\\(\\s*${publishStagePattern}\\s*===\\s*['"]${stageId}['"]\\s*\\)\\s*validate${stageId}Report\\s*\\(\\s*${publishReportPattern}\\s*\\)`);
  assert(dispatchPattern.test(dispatchBlock), `${stageId} must dispatch only its matching report validator`);
}
const validatorDispatchCalls = dispatchBlock.match(/validateL(?:43|44|45|46)Report\s*\(/g) ?? [];
assert(validatorDispatchCalls.length === 4, 'Publish verifier must dispatch exactly four historical Stage validators');
assert(/function\s+fixtureTodoItems\s*\(/.test(compactVerifier), 'Publish verifier must retain fixtureTodoItems');
const fixtureStart = compactVerifier.indexOf('const scannerDefinitionFixture');
const fixtureEnd = compactVerifier.indexOf('const report = validateCommonReport', fixtureStart);
assert(fixtureStart >= 0 && fixtureEnd > fixtureStart, 'TODO fixture block must have stable boundaries');
const fixtureBlock = compactVerifier.slice(fixtureStart, fixtureEnd);
for (const fixtureName of ['scannerDefinitionFixture', 'realTodoFixture', 'verifierFixture']) assert(fixtureBlock.includes(`const ${fixtureName}`), `TODO fixture must retain ${fixtureName}`);
assert(/fixtureTodoItems\s*\(\s*['"]scripts\/generate-stage-report\.ts['"]\s*,\s*scannerDefinitionFixture\s*\)\.length\s*===\s*0/.test(fixtureBlock), 'Scanner implementation fixture must produce zero TODO rows');
assert(/fixtureTodoItems\s*\(\s*['"]apps\/api\/src\/services\/reward-example\.ts['"]\s*,\s*realTodoFixture\s*\)\.length\s*===\s*1/.test(fixtureBlock), 'Real business TODO fixture must produce one TODO row');
assert(/fixtureTodoItems\s*\(\s*['"]scripts\/verify-example-local\.ts['"]\s*,\s*verifierFixture\s*\)\.length\s*===\s*0/.test(fixtureBlock), 'Verifier TODO assertion fixture must produce zero TODO rows');
console.log('Report stage routing checks passed.');
