import { useEffect, useState } from "react";
import { Button, Card, Form, Input, InputNumber, Space, Switch, Table, Typography } from "antd";
import { disableDeliveryRuleConfig, listDeliveryRuleConfigs, saveDeliveryRuleConfig, type DeliveryRuleConfig } from "../../api/delivery";

const defaultWindows = JSON.stringify([{ code: "today_afternoon", label: "今日下午", start_time: "14:00", end_time: "18:00" }, { code: "today_evening", label: "今日晚上", start_time: "18:00", end_time: "21:00" }, { code: "tomorrow_morning", label: "明日上午", start_time: "09:00", end_time: "12:00" }], null, 2);
const TextArea = (Input as any).TextArea;
function assertWindows(value: string) { const parsed = JSON.parse(value); if (!Array.isArray(parsed)) throw new Error("available_time_windows 必须是数组"); parsed.forEach((item: any) => { if (!item.code || !item.label || !item.start_time || !item.end_time) throw new Error("每项包含 code/label/start_time/end_time"); }); return parsed; }

export function DeliveryRuleConfigPage() {
  const [items, setItems] = useState<DeliveryRuleConfig[]>([]);
  const [editing, setEditing] = useState<DeliveryRuleConfig | null>(null);
  const [message, setMessage] = useState("");
  const [formKey, setFormKey] = useState(0);
  const [initialValues, setInitialValues] = useState<any>({ enabled: true, base_fee_cents: 0, pickup_store_id: "", service_radius_text: "门店周边 3-5km，具体以门店确认为准", notice: "当前为门店配送，暂不接第三方配送。配送范围与时段以门店确认为准。", available_time_windows: defaultWindows });
  async function load() { const rows = await listDeliveryRuleConfigs(); setItems(rows.items); }
  useEffect(() => { void load(); }, []);
  function edit(row?: DeliveryRuleConfig) { setEditing(row ?? null); setInitialValues(row ? { ...row, available_time_windows: JSON.stringify(row.available_time_windows, null, 2) } : { enabled: true, base_fee_cents: 0, free_threshold_cents: null, max_distance_km: null, pickup_store_id: "", service_radius_text: "门店周边 3-5km，具体以门店确认为准", notice: "当前为门店配送，暂不接第三方配送。配送范围与时段以门店确认为准。", available_time_windows: defaultWindows }); setFormKey((v) => v + 1); }
  async function save(values: any) { const base_fee_cents = Number(values.base_fee_cents); const free_threshold_cents = values.free_threshold_cents === null || values.free_threshold_cents === undefined || values.free_threshold_cents === "" ? null : Number(values.free_threshold_cents); if (base_fee_cents < 0 || (free_threshold_cents != null && free_threshold_cents < 0)) throw new Error("金额字段必须大于等于 0"); const windows = assertWindows(values.available_time_windows); await saveDeliveryRuleConfig({ id: editing?.id, pickup_store_id: values.pickup_store_id || null, enabled: Boolean(values.enabled), base_fee_cents, free_threshold_cents, max_distance_km: values.max_distance_km ?? null, service_radius_text: values.service_radius_text, notice: values.notice, available_time_windows: windows }); setMessage("保存成功"); edit(); await load(); }
  async function disable(row: DeliveryRuleConfig) { await disableDeliveryRuleConfig(row.id); setMessage("禁用成功"); await load(); }
  return <Space direction="vertical" style={{ width: "100%" }}>
    <Card title="配送规则配置"><Typography.Paragraph>支持全局默认规则与自提点规则；自提点规则优先。仅配置门店配送，不新增第三方配送配置。</Typography.Paragraph>{message ? <Typography.Text type="secondary">{message}</Typography.Text> : null}<Button onClick={() => edit()} type="primary">新建规则</Button></Card>
    <Table rowKey="id" dataSource={items} columns={[{ title: "规则 ID", dataIndex: "id" }, { title: "适用自提点", render: (_: unknown, row: DeliveryRuleConfig) => row.pickup_store_id || "全局默认规则" }, { title: "enabled", dataIndex: "enabled", render: (v: boolean) => String(v) }, { title: "base_fee_cents", dataIndex: "base_fee_cents" }, { title: "free_threshold_cents", dataIndex: "free_threshold_cents" }, { title: "service_radius_text", dataIndex: "service_radius_text" }, { title: "available_time_windows", render: (_: unknown, row: DeliveryRuleConfig) => row.available_time_windows.map((w) => w.code).join(", ") }, { title: "updated_at", dataIndex: "updated_at" }, { title: "操作", render: (_: unknown, row: DeliveryRuleConfig) => <Space><Button onClick={() => edit(row)}>编辑</Button><Button danger onClick={() => disable(row)}>禁用</Button></Space> }]} />
    <Card title={editing ? "编辑配送规则配置" : "新建配送规则配置"}><Form key={formKey} layout="vertical" onFinish={save} initialValues={initialValues}><Form.Item label="pickup_store_id（空表示全局默认规则）" name="pickup_store_id"><Input placeholder="空表示全局默认规则；填写则为自提点规则" /></Form.Item><Form.Item label="enabled" name="enabled" valuePropName="checked"><Switch /></Form.Item><Form.Item label="base_fee_cents" name="base_fee_cents" rules={[{ required: true }]}><InputNumber min={0} /></Form.Item><Form.Item label="free_threshold_cents" name="free_threshold_cents"><InputNumber min={0} /></Form.Item><Form.Item label="max_distance_km" name="max_distance_km"><InputNumber min={0} /></Form.Item><Form.Item label="service_radius_text" name="service_radius_text" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="notice" name="notice" rules={[{ required: true }]}><TextArea rows={2} /></Form.Item><Form.Item label="available_time_windows JSON" name="available_time_windows" rules={[{ required: true }]}><TextArea rows={8} /></Form.Item><Button htmlType="submit" type="primary">保存</Button></Form></Card>
  </Space>;
}
