import { Prisma } from '@prisma/client';
import { prisma } from '../../db.js';

export type OperationsQuery = { from?: string; to?: string; community_id?: string; pickup_store_id?: string; days?: number; sort_by?: string; limit?: number; type?: string };
export function sumOrZero(value: number | null | undefined): number { return value ?? 0; }
function dateWhere(query: Pick<OperationsQuery, 'from' | 'to'>): Prisma.DateTimeFilter | undefined { const where: Prisma.DateTimeFilter = {}; if (query.from) where.gte = new Date(query.from); if (query.to) where.lte = new Date(query.to); return Object.keys(where).length ? where : undefined; }
function orderWhere(query: OperationsQuery): Prisma.OrderWhereInput { return { created_at: dateWhere(query), community_id: query.community_id, pickup_store_id: query.pickup_store_id }; }
function sum(values: Array<number | null | undefined>) { return values.reduce((total, value) => total + sumOrZero(value), 0); }
function rate(numerator: number, denominator: number) { return denominator > 0 ? numerator / denominator : 0; }
function dayKey(date: Date) { return date.toISOString().slice(0, 10); }
function startOfDay(date: Date) { const next = new Date(date); next.setUTCHours(0, 0, 0, 0); return next; }
function addDays(date: Date, days: number) { const next = new Date(date); next.setUTCDate(next.getUTCDate() + days); return next; }
async function scopedOrders(query: OperationsQuery) { return prisma.order.findMany({ where: orderWhere(query), include: { after_sale_cases: true, commissions: true, group_buy: { include: { product: { include: { category: true } }, community: true } }, community: true, pickup_store: true } }); }

export async function getOperationsOverview(query: OperationsQuery) {
  const orders = await scopedOrders(query); const paidOrders = orders.filter((order) => order.pay_status === 'paid');
  const [inventoryLosses, activeGroupBuyCount, activeProductCount, activeCommunityCount] = await Promise.all([
    prisma.inventoryLoss.findMany({ where: { created_at: dateWhere(query) }, include: { product: true } }),
    prisma.groupBuy.count({ where: { status: { in: ['pending', 'success', 'preparing', 'ready'] }, community_id: query.community_id } }),
    prisma.product.count({ where: { status: 'active' } }),
    prisma.community.count({ where: { status: 'active' } })
  ]);
  const afterSaleCaseCount = sum(orders.map((order) => order.after_sale_cases.length)); const paidAmount = sum(paidOrders.map((order) => order.pay_amount_cents)); const refundedAmount = sum(orders.map((order) => order.refund_amount_cents));
  return { order_count: orders.length, paid_order_count: paidOrders.length, completed_order_count: orders.filter((order) => order.order_status === 'completed').length, cancelled_order_count: orders.filter((order) => ['closed', 'refunded'].includes(order.order_status)).length, gross_sales_amount: sum(orders.map((order) => order.total_amount_cents)), paid_amount: paidAmount, refunded_amount: refundedAmount, net_sales_amount: paidAmount - refundedAmount, after_sale_case_count: afterSaleCaseCount, after_sale_rate: rate(afterSaleCaseCount, paidOrders.length), refund_rate: rate(refundedAmount, paidAmount), pickup_completed_count: orders.filter((order) => ['picked', 'completed'].includes(order.order_status)).length, pickup_pending_count: orders.filter((order) => order.order_status === 'ready').length, inventory_loss_count: inventoryLosses.length, inventory_loss_estimated_amount: sum(inventoryLosses.map((loss) => loss.quantity * loss.product.cost_price_cents)), service_reward_amount: sum(orders.flatMap((order) => order.commissions.map((item) => item.final_amount_cents))), active_group_buy_count: activeGroupBuyCount, active_product_count: activeProductCount, active_community_count: activeCommunityCount };
}
export async function getOperationsTrends(query: OperationsQuery) { const days = Math.min(31, Math.max(1, query.days ?? 7)); const today = startOfDay(new Date()); const from = addDays(today, -(days - 1)); const to = addDays(today, 1); const orders = await scopedOrders({ ...query, from: from.toISOString(), to: to.toISOString() }); const losses = await prisma.inventoryLoss.findMany({ where: { created_at: { gte: from, lt: to } } }); return Array.from({ length: days }, (_, index) => dayKey(addDays(from, index))).map((date) => { const dayOrders = orders.filter((order) => dayKey(order.created_at) === date); const paid = dayOrders.filter((order) => order.pay_status === 'paid'); const paidAmount = sum(paid.map((order) => order.pay_amount_cents)); const refundedAmount = sum(dayOrders.map((order) => order.refund_amount_cents)); return { date, order_count: dayOrders.length, paid_amount: paidAmount, refunded_amount: refundedAmount, net_sales_amount: paidAmount - refundedAmount, after_sale_case_count: sum(dayOrders.map((order) => order.after_sale_cases.length)), inventory_loss_count: losses.filter((loss) => dayKey(loss.created_at) === date).length, pickup_completed_count: dayOrders.filter((order) => ['picked', 'completed'].includes(order.order_status)).length }; }); }
export async function getOperationsProducts(query: OperationsQuery) { const orders = await scopedOrders(query); const losses = await prisma.inventoryLoss.findMany({ where: { created_at: dateWhere(query) } }); const rows = new Map<string, Record<string, any>>(); for (const order of orders) { const product = order.group_buy?.product; if (!product) continue; const row = rows.get(product.id) ?? { product_id: product.id, product_name: product.name, category_name: product.category.name, order_count: 0, quantity_sold: 0, paid_amount: 0, refunded_amount: 0, net_sales_amount: 0, after_sale_case_count: 0, after_sale_rate: 0, inventory_loss_count: 0 }; row.order_count += 1; row.quantity_sold += order.quantity; row.paid_amount += order.pay_status === 'paid' ? order.pay_amount_cents : 0; row.refunded_amount += order.refund_amount_cents; row.after_sale_case_count += order.after_sale_cases.length; rows.set(product.id, row); } for (const row of rows.values()) { row.net_sales_amount = row.paid_amount - row.refunded_amount; row.after_sale_rate = rate(row.after_sale_case_count, row.order_count); row.inventory_loss_count = losses.filter((loss) => loss.product_id === row.product_id).length; } const sort = query.sort_by ?? 'sales_amount'; const key = sort === 'refund_amount' ? 'refunded_amount' : sort === 'after_sale_count' ? 'after_sale_case_count' : sort === 'order_count' ? 'order_count' : 'paid_amount'; return [...rows.values()].sort((a, b) => b[key] - a[key]).slice(0, Math.min(100, Math.max(1, query.limit ?? 20))); }
export async function getOperationsCommunities(query: OperationsQuery) { const orders = await scopedOrders(query); const rows = new Map<string, Record<string, any>>(); for (const order of orders) { const community = order.community ?? order.group_buy?.community; if (!community) continue; const row = rows.get(community.id) ?? { community_id: community.id, community_name: community.name, order_count: 0, paid_amount: 0, refunded_amount: 0, net_sales_amount: 0, pickup_completed_count: 0, after_sale_case_count: 0, active_group_buy_count: 0 }; row.order_count += 1; row.paid_amount += order.pay_status === 'paid' ? order.pay_amount_cents : 0; row.refunded_amount += order.refund_amount_cents; row.pickup_completed_count += ['picked', 'completed'].includes(order.order_status) ? 1 : 0; row.after_sale_case_count += order.after_sale_cases.length; rows.set(community.id, row); } for (const row of rows.values()) { row.net_sales_amount = row.paid_amount - row.refunded_amount; row.active_group_buy_count = await prisma.groupBuy.count({ where: { community_id: row.community_id, status: { in: ['pending', 'success', 'preparing', 'ready'] } } }); } return [...rows.values()].sort((a, b) => b.paid_amount - a.paid_amount); }
export async function getOperationsPickupStores(query: OperationsQuery) { const orders = await scopedOrders(query); const rows = new Map<string, Record<string, any>>(); for (const order of orders) { const store = order.pickup_store; if (!store) continue; const row = rows.get(store.id) ?? { pickup_store_id: store.id, pickup_store_name: store.name, order_count: 0, pickup_completed_count: 0, pickup_pending_count: 0, pickup_completion_rate: 0, paid_amount: 0, after_sale_case_count: 0 }; row.order_count += 1; row.pickup_completed_count += ['picked', 'completed'].includes(order.order_status) ? 1 : 0; row.pickup_pending_count += order.order_status === 'ready' ? 1 : 0; row.paid_amount += order.pay_status === 'paid' ? order.pay_amount_cents : 0; row.after_sale_case_count += order.after_sale_cases.length; rows.set(store.id, row); } for (const row of rows.values()) row.pickup_completion_rate = rate(row.pickup_completed_count, row.order_count); return [...rows.values()].sort((a, b) => b.pickup_completed_count - a.pickup_completed_count); }
export async function getOperationsAlerts(query: OperationsQuery) { const overview = await getOperationsOverview(query); const alerts: Array<Record<string, unknown>> = []; const push = (type: string, severity: string, title: string, description: string, metric_value: number) => alerts.push({ type, severity, title, description, metric_value }); if (overview.after_sale_rate > 0.2) push('high_after_sale_rate', 'high', '售后率偏高', '请关注商品质量、履约和客服处理情况。', overview.after_sale_rate); if (overview.refunded_amount > 0) push('high_refund_amount', overview.refund_rate > 0.2 ? 'high' : 'medium', '退款金额需关注', '请核对退款原因和售后记录。', overview.refunded_amount); if (overview.inventory_loss_count > 0) push('high_inventory_loss', 'medium', '存在库存损耗', '请复盘损耗商品、批次与责任记录。', overview.inventory_loss_count); if (overview.pickup_pending_count > 10) push('pickup_pending_too_many', 'medium', '待自提订单较多', '请提醒门店核对待自提订单。', overview.pickup_pending_count); if (overview.active_product_count < 3) push('low_active_products', 'low', '在售商品较少', '请评估是否需要补充可售商品。', overview.active_product_count); return alerts; }
export function toOperationsCsv(rows: Array<Record<string, unknown>>) { const headers = Object.keys(rows[0] ?? { empty: '' }); const esc = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`; return ['\uFEFF' + headers.join(','), ...rows.map((row) => headers.map((key) => esc(row[key])).join(','))].join('\n'); }
